services:

  tempo:
    image: grafana/tempo:latest
    container_name: unikly-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "4318:4318"
      - "3200:3200"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml:ro
      - unikly-tempo-data:/var/tempo
    networks:
      - unikly-net

  prometheus:
    image: prom/prometheus:latest
    container_name: unikly-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - unikly-net

  grafana:
    image: grafana/grafana:latest
    container_name: unikly-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - unikly-grafana-data:/var/lib/grafana
    networks:
      - unikly-net

networks:
  unikly-net:
    external: true
    name: infra_unikly-net

volumes:
  unikly-grafana-data:
  unikly-tempo-data:
