CREATE TABLE customer_carts (
    id VARCHAR(36) PRIMARY KEY,
    buyer_id BIGINT NOT NULL UNIQUE REFERENCES store_users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_customer_carts_buyer_id ON customer_carts(buyer_id);

CREATE TABLE customer_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id VARCHAR(36) NOT NULL REFERENCES customer_carts(id) ON DELETE CASCADE,
    product_id VARCHAR(36) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
);

CREATE INDEX ix_customer_cart_items_cart_id ON customer_cart_items(cart_id);
CREATE INDEX ix_customer_cart_items_product_id ON customer_cart_items(product_id);
