CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(36) NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,
    buyer_id BIGINT NOT NULL REFERENCES store_users(id) ON DELETE CASCADE,
    author_name VARCHAR(120) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    title VARCHAR(120) NOT NULL,
    comment TEXT NOT NULL,
    is_verified_purchase BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_product_reviews_product_buyer UNIQUE (product_id, buyer_id)
);

CREATE INDEX ix_product_reviews_product_id ON product_reviews(product_id);
CREATE INDEX ix_product_reviews_buyer_id ON product_reviews(buyer_id);
CREATE INDEX ix_product_reviews_product_created ON product_reviews(product_id, created_at DESC);
