CREATE TABLE customer_orders (
    id VARCHAR(36) PRIMARY KEY,
    reference VARCHAR(20) NOT NULL UNIQUE,
    buyer_id BIGINT NOT NULL REFERENCES store_users(id) ON DELETE CASCADE,
    status VARCHAR(24) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    address_line_1 VARCHAR(160) NOT NULL,
    address_line_2 VARCHAR(160),
    city VARCHAR(100) NOT NULL,
    region VARCHAR(100) NOT NULL,
    postal_code VARCHAR(24) NOT NULL,
    country VARCHAR(80) NOT NULL,
    total NUMERIC(12, 2) NOT NULL CHECK (total >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_customer_orders_buyer_created_at ON customer_orders(buyer_id, created_at DESC);
CREATE TABLE customer_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL REFERENCES customer_orders(id) ON DELETE CASCADE,
    product_id VARCHAR(36) NOT NULL,
    product_name VARCHAR(120) NOT NULL,
    seller_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price > 0)
);
CREATE INDEX ix_customer_order_items_order_id ON customer_order_items(order_id);
