package com.unikly.userservice.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

@Schema(description = "Request payload used to exchange social OAuth code with Keycloak")
public record SocialCodeExchangeRequest(
        @Schema(description = "Authorization code returned by Keycloak")
        @NotBlank
        @Size(max = 2048)
        String code,

        @Schema(description = "Same redirect URI used during authorization")
        @NotBlank
        @Size(max = 1024)
        String redirectUri,

        @Schema(description = "PKCE code verifier generated by frontend")
        @NotBlank
        @Size(max = 255)
        String codeVerifier
) {}
